export const skillsOptions = [
  {
    heading: "Frontend",
    options: [
      { value: "react", label: "React" },
      { value: "svelte", label: "Svelte" },
      { value: "angular", label: "Angular" },
      { value: "vue", label: "Vue" },
      { value: "solidjs", label: "SolidJS" },
      { value: "redux", label: "Redux" },
      { value: "elm", label: "Elm" },
      { value: "jquery", label: "jQuery" },
      { value: "tailwind-css", label: "Tailwind CSS" },
      { value: "bootstrap", label: "Bootstrap" },
      { value: "material-ui", label: "Material UI" },
      { value: "chakra-ui", label: "Chakra UI" },
      { value: "ant-design", label: "Ant Design" },
    ],
  },
  {
    heading: "Backend",
    options: [
      { value: "javascript", label: "Javascript" },
      { value: "typescript", label: "Typescript" },
      { value: "node-js", label: "Node.js" },
      { value: "php", label: "PHP" },
      { value: "laravel", label: "Laravel" },
      { value: "python", label: "Python" },
      { value: "django", label: "Django" },
      { value: "kotlin", label: "Kotlin" },
      { value: "swift", label: "Swift" },
      { value: "go", label: "Go" },
      { value: "rust", label: "Rust" },
      { value: "ruby-on-rails", label: "Ruby on Rails" },
      { value: "asp-net", label: "ASP.NET" },
      { value: "express", label: "Express" },
      { value: "fastapi", label: "FastAPI" },
      { value: "flask", label: "Flask" },
    ],
  },
  {
    heading: "Database",
    options: [
      { value: "mysql", label: "MySQL" },
      { value: "postgresql", label: "PostgreSQL" },
      { value: "mongodb", label: "MongoDB" },
      { value: "sqlite", label: "SQLite" },
      { value: "redis", label: "Redis" },
    ],
  },
  {
    heading: "DevOps",
    options: [
      { value: "docker", label: "Docker" },
      { value: "kubernetes", label: "Kubernetes" },
      { value: "jenkins", label: "Jenkins" },
      { value: "github-actions", label: "Github Actions" },
    ],
  },
  {
    heading: "Mobile",
    options: [
      { value: "android", label: "Android" },
      { value: "ios", label: "iOS" },
      { value: "flutter", label: "Flutter" },
      { value: "react-native", label: "React Native" },
      { value: "swiftui", label: "SwiftUI" },
      { value: "jetpack-compose", label: "Jetpack Compose" },
      { value: "xamarin", label: "Xamarin" },
    ],
  },
  {
    heading: "Blockchain",
    options: [
      { value: "smart-contracts", label: "Smart Contracts" },
      { value: "ink", label: "ink!" },
      { value: "solidity", label: "Solidity" },
      { value: "substrate", label: "Substrate" },
      { value: "polkadot-sdk", label: "Polkadot SDK" },
      { value: "dedot", label: "Dedot" },
      { value: "polkadot-api-sdk", label: "Polkadot API SDK" },
    ],
  },
  {
    heading: "Design",
    options: [
      { value: "ui-ux-design", label: "UI/UX Design" },
      { value: "motion-design", label: "Motion Design" },
      { value: "graphic-design", label: "Graphic Design" },
      { value: "illustration", label: "Illustration" },
      { value: "game-design", label: "Game Design" },
      { value: "presentation-design", label: "Presentation Design" },
    ],
  },
  {
    heading: "Community",
    options: [
      { value: "community-manager", label: "Community Manager" },
      { value: "discord-moderator", label: "Discord Moderator" },
      { value: "telegram-moderator", label: "Telegram Moderator" },
      { value: "reddit-moderator", label: "Reddit Moderator" },
    ],
  },
  {
    heading: "Growth",
    options: [
      { value: "business-development", label: "Business Development" },
      { value: "digital-marketing", label: "Digital Marketing" },
      { value: "marketing", label: "Marketing" },
    ],
  },
  {
    heading: "Content",
    options: [
      { value: "research", label: "Research" },
      { value: "photography", label: "Photography" },
      { value: "video", label: "Video" },
      { value: "video-editing", label: "Video Editing" },
      { value: "writing", label: "Writing" },
      { value: "technical-writing", label: "Technical Writing" },
      { value: "social-media", label: "Social Media" },
    ],
  },
  {
    heading: "Product",
    options: [
      { value: "product-manager", label: "Product Manager" },
      { value: "product-owner", label: "Product Owner" },
      { value: "product-designer", label: "Product Designer" },
      { value: "product-analyst", label: "Product Analyst" },
    ],
  },
  {
    heading: "Other",
    options: [
      { value: "data-analytics", label: "Data Analytics" },
      { value: "operations", label: "Operations" },
      { value: "product-feedback", label: "Product Feedback" },
      { value: "quality-assurance", label: "Quality Assurance" },
    ],
  },
];